import { Activity } from 'lucide-react';

function LiveBar({ label, value }) {
  return (
    <div>
      <div className="mb-1 flex justify-between text-xs">
        <span className="text-text-muted">{label}</span>
        <span className="font-medium">{value}%</span>
      </div>
      <div className="h-1.5 w-full overflow-hidden rounded-full bg-secondary">
        <div
          className="h-full rounded-full bg-gradient-accent transition-all duration-500 ease-out"
          style={{ width: `${value}%` }}
        />
      </div>
    </div>
  );
}

export default function LiveEvaluation({ metrics, isRecording }) {
  return (
    <div className="glass-card p-4">
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2 text-sm font-semibold text-text-muted">
          <Activity size={16} className={isRecording ? 'animate-pulse text-success' : 'text-text-dim'} />
          Live Signals
        </div>
        <span className="font-mono text-xs text-text-dim">{metrics.wpm} wpm</span>
      </div>

      <div className="space-y-3">
        <LiveBar label="Confidence" value={metrics.confidence} />
        <LiveBar label="Fluency" value={metrics.fluency} />
        <LiveBar label="Pace" value={metrics.pace} />
      </div>

      <p className="mt-4 text-xs leading-relaxed text-text-dim">
        Rough, in-the-moment estimates from your speaking pace and filler words. Your full scored
        report — confidence, communication, grammar, technical depth, and more — is generated by
        Gemini once you finish the interview.
      </p>
    </div>
  );
}
